### ISSUE TITLE
 jslingua_docs is outdated!

### ISSUE THREAD

**Issue by shilik** [kariminf/jslingua_examples#1]
@kariminf  Thanks for the interesting projects. I am trying to use the examples in jslingua_docs  for Japanese trans and morpho modules, but it turns out that many functions didn't work as expected.
Can you update the doc as well? Thank you!

**Comment by kariminf** [comment]
@shilik  Thank you for your feedback.

It will be updated soon. Since version 0.13, a lot has been changed (Now, the package is packed into one file, also no need to instantiate the classes since they have static functions)
